language: elixir
elixir:
  - 1.1.1
  - 1.2.0-rc.0
  - 1.3.3
otp_release:
  - 18.0
  - 19.0
sudo: false
install: mix local.hex --force
script:
  - make
notifications:
  irc: "irc.freenode.org#emacs-elixir"
